### ISSUE TITLE
Oops! unintentional push to the Course-Assets repo

### ISSUE THREAD

**Issue by sbchittenden** [moderndeveloper-students/Course-Assets#1]
@mrvdot 

Hi Alex -  Apologies, I was working through the Frontend tooling chapter and accidentally pushed via the grunt deploy task (evidently I have write permissions).  It was just a version update (1.1.3 to 1.1.4). I don't want to mess with the repo anymore than I already have so I will leave the revert to you. Sorry about that.

**Comment by mrvdot** [comment]
@sbchittenden No worries man, that small of a change is no problem. I will talk to @richardbov however about removing write privileges so bigger changes aren't accidentally pushed as well.

Thanks for catching that,
Alex
